### ISSUE TITLE
Uses for the Info endpoint

### ISSUE THREAD

**Issue by Idane** [krud-dev/ostara#200]
```json 
{
  "git" : {
    "branch" : "main",
    "commit" : {
      "id" : "df027cf",
      "time" : "2023-03-03T17:27:49Z"
    }
  },
  "build" : {
    "artifact" : "application",
    "version" : "1.0.3",
    "group" : "com.example"
  }
}
```

**Comment by thewizkid87** [comment]
I think have it as a badge next to the Up, displays version
![image](https://github.com/krud-dev/ostara/assets/39795021/cc99da3e-cf64-43d7-add0-1b68afdcd457)

On click open modal with all details

I think we should also add to the instance tabe in the app menu - version, git commit id and maybe have a warning message if not all matching

**Comment by Idane** [comment]
1. Probe adding version to instance RO with performance in mind

**Comment by Idane** [comment]
Handled in #482 and #483
