### ISSUE TITLE
Have "demo" env that is preconfigured (read only)

### ISSUE THREAD

**Issue by thewizkid87** [krud-dev/ostara#216]
Flow:

Demo will be a separate jar which will be either bundled, part of the main jar, or downloaded separately.
Upon "demo creation", the demo process will start up on a random port. Once done, a read only folder, application and instance will be created. They should not be movable or editable in any way (including color and icon) with an explanation on why they can't be edited (e.g. make a special visual distinction for demo instances).

* Make a special endpoint to create this trio, do not use the standard crud
* Need to find a way to distinct the trio, maybe an `isDemo` field to folder/app/instance
* If the tree is empty, add the button to run the demo. Otherwise, need to think on where to make it accessible
* Upon app close, terminate the process
* Upon app open, if demo trio exists, delete it (User can run the demo again manually, but do not add the overhead of starting up the demo to each app start)

Features:

- Loggers
- Caches
- Dashboard
- Integration Graph
- Changing thread counts for graph diversity
- Simulated web requests / mock API
- Quartz / Scheduled Tasks
- Flyway OR Liquibase
- Example app properties
- Usage of profiles

**Comment by avivm** [comment]
Create demo button on empty sidebar amd on getting started in home
startDemo
createDemoApplication with url
on create demo auto select instance
disable DND for demo
Unreable view adjustments for demo -> Demo service is loading (It can take up to a minute to load) -> Refresh Status, Restart Demo (Stop + Start), Remove Demo
Disable update for demo application/instance
Allow delete demo application with stopDemo
Disable delete demo instance
