### ISSUE TITLE
Application health status is EMPTY even though the instance count is 3

### ISSUE THREAD

**Issue by avivm** [krud-dev/ostara#364]
I moved instances in the application using DND.

![Screenshot 2023-04-20 at 17 05 06](https://user-images.githubusercontent.com/3274500/233392052-17aedecd-b2be-487b-a6c0-18e870df33b6.png)
![Screenshot 2023-04-20 at 17 05 00](https://user-images.githubusercontent.com/3274500/233392063-90345d3f-b0b0-43a1-b337-0de8fec38b55.png)

**Comment by Idane** [comment]
Hopefully solved by #464 , otherwise no longer relevant as moving instances between apps has been disallowed
