### ISSUE TITLE
Connection to instance failed. Status Code: 500. Message: 500 INTERNAL_SERVER_ERROR "Actuator request failed: Request{method=GET, url=https://127.0.0.1:18888/actuator}"

### ISSUE THREAD

**Issue by defrimhasani** [krud-dev/ostara#390]
I have a service with actuator running on https://localhost:18888/actuator, and boost can't connect to it with the following error.

![image](https://user-images.githubusercontent.com/33935491/236444986-f823c969-d44f-4ebe-b1f8-9762fb63a9f1.png)

The service is up and running and accessible by insomnia, see timeline

* Preparing request to https://127.0.0.1:18888/actuator
* Current time is 2023-05-05T11:18:43.087Z
* Enable automatic URL encoding
* Using default HTTP version
* Disable SSL validation
* Enable cookie sending with jar of 1 cookie
* Too old connection (927 seconds), disconnect it
* Connection 6 seems to be dead!
* Closing connection 6
* TLSv1.2 (OUT), TLS header, Unknown (21):
* Too old connection (923 seconds), disconnect it
* Connection 7 seems to be dead!
* Closing connection 7
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.2 (IN), TLS alert, close notify (256):
* TLSv1.2 (OUT), TLS header, Unknown (21):
*   Trying 127.0.0.1:18888...
* Connected to 127.0.0.1 (127.0.0.1) port 18888 (#8)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
// hidden
* TLSv1.2 (OUT), TLS header, Supplemental data (23):

> GET /actuator HTTP/1.1
> Host: 127.0.0.1:18888
> User-Agent: insomnia/2023.2.0
> Accept: */*

* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse

< HTTP/1.1 200 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-Frame-Options: DENY
< Content-Type: application/vnd.spring-boot.actuator.v3+json
< Transfer-Encoding: chunked
< Date: Fri, 05 May 2023 11:18:43 GMT

* Received 598 B chunk
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Received 5 B chunk
* Connection #8 to host 127.0.0.1 left intact

**Comment by Idane** [comment]
@defrimhasani Sorry for the late response, could you give me a rough outline of your service spring dependencies so that I can try to reproduce? Is your certificate legitimate or self signed?

**Comment by Idane** [comment]
I definitely think there is room for it in settings, as well as more clearly defined and displayed SSL errors

**Comment by Idane** [comment]
Release in 0.9.0
