### ISSUE TITLE
Disable SSL validation

### ISSUE THREAD

**Issue by Absolutely17** [krud-dev/ostara#413]
## Summary
Can i disable SSL validation? I have an application on the dev stand, but it has a self-signed certificate on the routing. I get an error "Failed to connect to instance with status 500 and message 500 INTERNAL_SERVER_ERROR "Actuator request failed: Request{method=GET, url=...}"

**Comment by Idane** [comment]
Not an option right now, but since it's been requested twice (#390) already, I'll look into implementing support. Thanks for the feedback!
