### ISSUE TITLE
Add Metric notifications

### ISSUE THREAD

**Issue by Idane** [krud-dev/ostara#417]
Add configurable OS notifications for metrics.

1. Above a threshold for X time
2. Below a threshold for X time
3. In a range for X time
4. ?

**Comment by Idane** [comment]
Instance level, application level or both?

**Comment by Idane** [comment]
TODO:
Add list of 'suggested' rules

**Comment by Idane** [comment]
Percentage changes:

* Add divisorMetricName
* Add divisorMetricName RuleInstanceAssociation 
* Add lastMetricValue
* Add lastDivisorValue to association
* Change lastValue to lastEvaluatedValue
* Subscribe to both when the rule is setup
* Add logic to update last evaluated value upon update

**Comment by avivm** [comment]
Add type (Simple/Relative/Adaptive - phase 2)
Add textual represntation of rule
Add explanation for each type
