### ISSUE TITLE
Add in-app feedback form

### ISSUE THREAD

**Issue by Idane** [krud-dev/ostara#447]
Action items:
1. Some form of (serverless) backend to intake requests (or find a SAAS)
2. UX/UI for the form

---

Add feedback button in
1. Help menu
2. Dashboard under feedback (Replace Send Email)
3. Add as an icon next to the settings cog

--- Feedback fields
- Text
- Optional email?

**Comment by avivm** [comment]
https://feqbilmwjizzspslglqi.functions.supabase.co/contact-request

curl --location 'https://feqbilmwjizzspslglqi.functions.supabase.co/contact-request' \
--header 'Content-Type: application/json' \
--data-raw '{
    "text": "Test\nNewline\nTest",
    "email": "some@email.com"
}'
