### ISSUE TITLE
"Shutdown" capability support

### ISSUE THREAD

**Issue by Idane** [krud-dev/ostara#52]
Actuator has an endpoint that allows to shutdown the server, need to integrate it into the instance page, potentially with a button and a confirmation dialog.

**Required ability:** Shutdown

If missing ability - don't show
Add a shutdown button to the sidebar of an instance
Once clicked, popup alert are you sure, "This will SHUTDOWN the instance - {instanceName}. Are you sure you want to proceed". With yes/no

**Comment by avivm** [comment]
Check disabled on application instances grid

**Comment by avivm** [comment]
When shutdown is disabled add explanation both grid and menu
